#!/usr/bin/env bash
set -e

HERMES_HOME="${HERMES_HOME:-/opt/data}"
PROFILE_CONFIG="/opt/hermes/profiles/default/config.yaml"
VOLUME_CONFIG="$HERMES_HOME/config.yaml"
VERSION="v17"

if [ -f "$PROFILE_CONFIG" ] && grep -q "CONFIG_VERSION: $VERSION" "$PROFILE_CONFIG" 2>/dev/null; then
    echo "[04-config-gen] Config $VERSION exists, skipping"
    exit 0
fi

echo "[04-config-gen] Generating config.yaml ($VERSION)..."

mkdir -p "$(dirname "$PROFILE_CONFIG")"
mkdir -p "$(dirname "$VOLUME_CONFIG")"

TEMP_CONFIG=$(mktemp)
cat > "$TEMP_CONFIG" << 'YAMLEOF'
# Generated by Railway startup — v17
# CONFIG_VERSION: v17

timezone: America/Chicago

gateway:
  model: anthropic/claude-opus-4-6
  provider: openrouter

platforms: {}

mcp_servers:
  # Remote gbrain knowledge brain, reached over HTTP with a static bearer.
  # DISABLED until the remote gbrain service is started with `serve --http --public-url`.
  # Token + URL are injected from Railway env vars (set them, then flip enabled: true).
  gbrain:
    enabled: false
    url: "${GBRAIN_MCP_URL}"
    headers:
      Authorization: "Bearer ${GBRAIN_MCP_TOKEN}"
    connect_timeout: 60
    read_timeout: 120

auxiliary:
  vision:
    provider: openrouter
    model: google/gemini-2.5-flash
YAMLEOF

cp "$TEMP_CONFIG" "$PROFILE_CONFIG"
cp "$TEMP_CONFIG" "$VOLUME_CONFIG"
rm -f "$TEMP_CONFIG"

echo "[04-config-gen] Config written to $PROFILE_CONFIG and $VOLUME_CONFIG"

# Auth: basic (username/password) provider satisfies the dashboard auth gate on a
# public bind. Configured via HERMES_DASHBOARD_BASIC_AUTH_* env vars on Railway.
# HERMES_DASHBOARD_INSECURE is a deprecated no-op on the hardened image — not used.
echo "[04-config-gen] Dashboard auth: basic provider (env-configured)"
