#!/usr/bin/env bash
set -e

HERMES_HOME="${HERMES_HOME:-/opt/data}"
PROFILE_CONFIG="/opt/hermes/profiles/default/config.yaml"
VOLUME_CONFIG="$HERMES_HOME/config.yaml"
VERSION="v13"
PASSWORD="${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD:-hermes-railway-22}"

if [ -f "$PROFILE_CONFIG" ] && grep -q "CONFIG_VERSION: $VERSION" "$PROFILE_CONFIG" 2>/dev/null; then
    echo "[04-config-gen] Config v13 exists, skipping"
    exit 0
fi

echo "[04-config-gen] Generating config.yaml..."

mkdir -p "$(dirname "$PROFILE_CONFIG")"
mkdir -p "$(dirname "$VOLUME_CONFIG")"

TEMP_CONFIG=$(mktemp)
cat > "$TEMP_CONFIG" << 'YAMLEOF'
# Generated by Railway startup — v13
# CONFIG_VERSION: v13

timezone: America/Chicago

gateway:
  model: deepseek/deepseek-v4-pro
  provider: openrouter

platforms: {}

mcp_servers:
  gbrain:
    command: gbrain
    args:
      - mcp
      - --source
      - default
    transport: stdio
    enabled: true

  slack:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-slack"
    enabled: false
    env:
      SLACK_BOT_TOKEN: ""
      SLACK_TEAM_ID: ""

  atlassian:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-atlassian"
    enabled: false
    env:
      ATLASSIAN_API_TOKEN: ""
      ATLASSIAN_DOMAIN: "bookmarked-team.atlassian.net"
      ATLASSIAN_EMAIL: "steve@bookmarked.com"

  hubspot:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-hubspot"
    enabled: false
    env:
      HUBSPOT_API_KEY: ""

auxiliary:
  vision:
    provider: openrouter
    model: google/gemini-2.5-flash

GATEWAY_ALLOW_ALL_USERS: "true"
HERMES_DASHBOARD: "1"
YAMLEOF

cp "$TEMP_CONFIG" "$PROFILE_CONFIG"
cp "$TEMP_CONFIG" "$VOLUME_CONFIG"
rm -f "$TEMP_CONFIG"

echo "[04-config-gen] Config written to $PROFILE_CONFIG and $VOLUME_CONFIG"

# Generate password hash INSIDE the container using Hermes' own function
echo "[04-config-gen] Generating password hash..."
HERMES_PYTHON="/opt/hermes/.venv/bin/python3"
HASH=$("$HERMES_PYTHON" -c "
from plugins.dashboard_auth.basic import hash_password
print(hash_password('$PASSWORD'))
" 2>/dev/null || echo "")

if [ -n "$HASH" ]; then
    mkdir -p /root/.hermes
    cat > /root/.hermes/.env << ENVEOF
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=steve
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH=$HASH
ENVEOF
    chmod 600 /root/.hermes/.env
    echo "[04-config-gen] Auth hash written to /root/.hermes/.env"
else
    echo "[04-config-gen] WARNING: Could not generate password hash — falling back to plaintext"
    mkdir -p /root/.hermes
    cat > /root/.hermes/.env << ENVEOF
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=steve
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=$PASSWORD
ENVEOF
    chmod 600 /root/.hermes/.env
fi