#!/usr/bin/env bash
set -e

# Generate config.yaml from environment variables on first run
# Writes to both the profile path (where gateway reads) and volume path (persistence)

HERMES_HOME="${HERMES_HOME:-/opt/data}"
# The gateway's profile system reads from this path
PROFILE_CONFIG="/opt/hermes/profiles/default/config.yaml"
# Also write to HERMES_HOME for volume persistence
VOLUME_CONFIG="$HERMES_HOME/config.yaml"
VERSION="v8"

if [ -f "$PROFILE_CONFIG" ] && grep -q "CONFIG_VERSION: $VERSION" "$PROFILE_CONFIG" 2>/dev/null; then
    echo "[04-config-gen] Config v8 exists, skipping"
    exit 0
fi

echo "[04-config-gen] Generating config.yaml..."

mkdir -p "$(dirname "$PROFILE_CONFIG")"
mkdir -p "$(dirname "$VOLUME_CONFIG")"

# Write the config to a temp file, then copy to both locations
TEMP_CONFIG=$(mktemp)
cat > "$TEMP_CONFIG" << 'YAMLEOF'
# Generated by Railway startup — v8 — edit via env vars and redeploy
# CONFIG_VERSION: v8

timezone: ${TIMEZONE:-America/Chicago}

gateway:
  model: ${HERMES_GATEWAY_MODEL:-deepseek/deepseek-v4-pro}
  provider: ${HERMES_GATEWAY_PROVIDER:-openrouter}

platforms: {}

# MCP Servers
mcp_servers:
  gbrain:
    command: gbrain
    args:
      - mcp
      - --source
      - default
    transport: stdio
    enabled: true

  slack:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-slack"
    enabled: ${MCP_SLACK_BOT_TOKEN:+true}
    env:
      SLACK_BOT_TOKEN: ${MCP_SLACK_BOT_TOKEN:-}
      SLACK_TEAM_ID: ${MCP_SLACK_TEAM_ID:-T05BP1VA8CX}

  atlassian:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-atlassian"
    enabled: ${ATLASSIAN_API_TOKEN:+true}
    env:
      ATLASSIAN_API_TOKEN: ${ATLASSIAN_API_TOKEN:-}
      ATLASSIAN_DOMAIN: ${ATLASSIAN_DOMAIN:-bookmarked-team.atlassian.net}
      ATLASSIAN_EMAIL: ${ATLASSIAN_EMAIL:-steve@bookmarked.com}

  hubspot:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-hubspot"
    enabled: ${HUBSPOT_API_KEY:+true}
    env:
      HUBSPOT_API_KEY: ${HUBSPOT_API_KEY:-}

  openmessage:
    command: npx
    args:
      - "-y"
      - "@anthropic/mcp-server-openmessage"
    enabled: false

auxiliary:
  vision:
    provider: openrouter
    model: google/gemini-2.5-flash

GATEWAY_ALLOW_ALL_USERS: "true"

HERMES_DASHBOARD: "1"

dashboard:
  basic_auth:
    username: ${DASHBOARD_USERNAME:-steve}
    password_hash: ${DASHBOARD_PASSWORD_HASH:-}
YAMLEOF

cp "$TEMP_CONFIG" "$PROFILE_CONFIG"
cp "$TEMP_CONFIG" "$VOLUME_CONFIG"
rm -f "$TEMP_CONFIG"

# Inject environment variable values (heredoc was quoted so vars are literal)
if [ -n "$MCP_SLACK_BOT_TOKEN" ]; then
    sed -i "s|\${MCP_SLACK_BOT_TOKEN:+true}|true|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
    sed -i "s|\${MCP_SLACK_BOT_TOKEN:-}|$MCP_SLACK_BOT_TOKEN|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
fi
if [ -n "$MCP_SLACK_TEAM_ID" ]; then
    sed -i "s|\${MCP_SLACK_TEAM_ID:-T05BP1VA8CX}|$MCP_SLACK_TEAM_ID|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
fi
if [ -n "$ATLASSIAN_API_TOKEN" ]; then
    sed -i "s|\${ATLASSIAN_API_TOKEN:+true}|true|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
    sed -i "s|\${ATLASSIAN_API_TOKEN:-}|$ATLASSIAN_API_TOKEN|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
fi
if [ -n "$HUBSPOT_API_KEY" ]; then
    sed -i "s|\${HUBSPOT_API_KEY:+true}|true|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
    sed -i "s|\${HUBSPOT_API_KEY:-}|$HUBSPOT_API_KEY|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
fi
if [ -n "$DASHBOARD_PASSWORD_HASH" ]; then
    sed -i "s|\${DASHBOARD_PASSWORD_HASH:-}|$DASHBOARD_PASSWORD_HASH|g" "$PROFILE_CONFIG" "$VOLUME_CONFIG"
fi

echo "[04-config-gen] Config written to $PROFILE_CONFIG and $VOLUME_CONFIG"